workflow fix

diff --git a/.github/workflows/infra.yaml b/.github/workflows/infra.yaml
--- a/.github/workflows/infra.yaml
+++ b/.github/workflows/infra.yaml
@@ -53,12 +53,12 @@ jobs:
       - name: Terraform Plan
         id: tf-plan
         run: |
-          terraform plan -input=false -out infra.plan -detailed-exitcode || exit_code=$?
-          exit_code=${exit_code:-0}
-          echo "exit-code=$exit_code" >> $GITHUB_OUTPUT
-
-          if [exit_code -eq 1]; then
-            echo "Error: Terraform plan failed."
+          terraform plan -input=false -out infra.plan -detailed-exitcode || exitcode=$?
+          exitcode=${exitcode:-0}
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+          
+          if [ $exitcode -eq 1 ]; then
+            echo "Terraform plan failed!"
             exit 1
           fi
 
