edit 22

diff --git a/.github/workflows/infra.yaml b/.github/workflows/infra.yaml
--- a/.github/workflows/infra.yaml
+++ b/.github/workflows/infra.yaml
@@ -16,6 +16,8 @@ jobs:
   plan:
     runs-on: ubuntu-latest
     environment: plan
+    outputs:
+      tf_exitcode: ${{ steps.tf-plan.outputs.exit-code }}
     steps:
       - name: checkout code
         uses: actions/checkout@v4
@@ -49,7 +51,16 @@ jobs:
         run: terraform validate
           
       - name: Terraform Plan
-        run: terraform plan -input=false -out infra.plan
+        id: tf-plan
+        run: |
+          terraform plan -input=false -out infra.plan -detailed-exitcode || exit_code=$?
+          exit_code=${exit_code:-0}
+          echo "exit-code=$exit_code" >> $GITHUB_OUTPUT
+
+          if [exit_code -eq 1]; then
+            echo "Error: Terraform plan failed."
+            exit 1
+          fi
 
       - name: upload the plan as artifact
         uses: actions/upload-artifact@v4
@@ -59,6 +70,7 @@ jobs:
 
   apply:
     needs: plan
+    if: needs.plan.outputs.tf_exitcode == '2'
     runs-on: ubuntu-latest
     environment: apply
     steps:
